In [1]:
import numpy as np 

In [5]:
import numpy as np

sales = np.array([
    [120, 150, 180, 200, 170, 210],
    [200, 220, 190, 250, 230, 270],
    [90, 110, 130, 100, 140, 150],
    [300, 280, 320, 350, 330, 370]
])

products = np.array([
    "Laptop",
    "Mobile",
    "Headphones",
    "Tablet"
])

months = np.array([
    "Jan", "Feb", "Mar", "Apr", "May", "Jun"
])

             Jan  Feb  Mar  Apr  May  Jun
Laptop       120  150  180  200  170  210
Mobile       200  220  190  250  230  270
Headphones    90  110  130  100  140  150
Tablet       300  280  320  350  330  370

#Task 1 :
find : 
1)shape
2)ndim
3)size
4)dtype

In [11]:
#Task 1 answers:
#1)
print(sales.shape)
#2)
print(sales.ndim)
#3) 
print(sales.size)
#4
print(sales.dtype)

(4, 6)
2
24
int64


# Task 2
1)Total products
2)Total months

In [16]:
#Task 2 answers:
#1)
print(products.size)
#2) 
print(months.size)


4
6


# Task 3
Part 2 — Sales Analysis

Find:

1)Total sales of all products
2)Average sales
3)Maximum sales
4)Minimum sales
5)Total sales product-wise
6)Total sales month-wise
7)Average sales product-wise
8)Average sales month-wise


In [35]:
# Task 3 answers :
#1) 
Total_sales= np.sum(sales)
print(Total_sales)
#2)
avg_sales=np.average(sales)
print(avg_sales)
#3) 
min_sales=np.min(sales)
print(min_sales)
#4)
max_sales=np.max(sales)
print(max_sales)
#5)
total_sales_product_wise = np.sum(sales, axis=1)
print(total_sales_product_wise)
#6)
total_sales_months_wise= np.sum(sales,axis=0)
print(total_sales_months_wise)
#7)
Avg_sales_product_wise = np.average(sales, axis=1)
print(Avg_sales_product_wise)
#8)
Avg_sales_months_wise= np.average(sales,axis=0)
print(Avg_sales_months_wise)

5060
210.83333333333334
90
370
[1030 1360  720 1950]
[ 710  760  820  900  870 1000]
[171.66666667 226.66666667 120.         325.        ]
[177.5 190.  205.  225.  217.5 250. ]


# Task 4:
Part 3 — Filtering

Find:

1)Sales greater than 250
2)Sales less than 150
3)Even sales values
4)Sales between 150 and 300

In [44]:
# Task 4 answers :
#1)
print(sales[sales>250])
#2)
print(sales[sales<150])
#3)
print (sales[sales%2==0])
print (sales[(sales>=150)&(sales<=300)])

[270 300 280 320 350 330 370]
[120  90 110 130 100 140]
[120 150 180 200 170 210 200 220 190 250 230 270  90 110 130 100 140 150
 300 280 320 350 330 370]
[150 180 200 170 210 200 220 190 250 230 270 150 300 280]


 # Task 5 
Part 4 — Business Logic

1)200 se greater sales ko "High" aur baaki ko "Low" label karo.
2)Har product ki best monthly sales find karo.
3)Har product ki worst monthly sales find karo.
4)Overall highest sales value find karo.

In [51]:
# Task 5 answers:
#1)
print(np.where(sales>200,"High","Low"))
#2)
best_monthly_sales=np.max(sales, axis=1)
print(best_monthly_sales)
#3)
worst_monthly_sales= np.min(sales,axis=1)
print(worst_monthly_sales)
#4) 
highest_sales=np.max(sales)
print(highest_sales)

[['Low' 'Low' 'Low' 'Low' 'Low' 'High']
 ['Low' 'High' 'Low' 'High' 'High' 'High']
 ['Low' 'Low' 'Low' 'Low' 'Low' 'Low']
 ['High' 'High' 'High' 'High' 'High' 'High']]
[210 270 150 370]
[120 190  90 280]
370


# Task 6 :
Part 5 — Broadcasting

Suppose company ne next month expected sales mein 10% growth assume ki.

Then find :

1)Expected sales
2)Additional expected sales
3)Product-wise expected sales

In [56]:
# task 6 answrers:
#1)
expected_sales = sales*1.10
print(expected_sales)

#2) additional_sales = expected_sale - current_sales
additional_sales= sales*1.10 - sales 
print(additional_sales)

#3)
product_wise_expected_sales = np.sum(sales*1.10, axis=1)
print(product_wise_expected_sales)

[[132. 165. 198. 220. 187. 231.]
 [220. 242. 209. 275. 253. 297.]
 [ 99. 121. 143. 110. 154. 165.]
 [330. 308. 352. 385. 363. 407.]]
[[12. 15. 18. 20. 17. 21.]
 [20. 22. 19. 25. 23. 27.]
 [ 9. 11. 13. 10. 14. 15.]
 [30. 28. 32. 35. 33. 37.]]
[1133. 1496.  792. 2145.]


# Task 7 
Business Questions

Q1. Which product has the highest total sales?

Q2. Which month has the highest total sales?

Q3. Overall average sales kitni hai?

Q4. Kitni sales 200 se greater hain?

Q5. 10% growth ke baad total expected sales kitni hogi?


In [60]:
# task 7 answers 
#1)
product_total = np.sum(sales, axis=1)
highest_product = products[np.argmax(product_total)]
print(highest_product)

#2)
month_total = np.sum(sales, axis=0)
highest_month = months[np.argmax(month_total)]
print(highest_month)

#3)
average_sales = np.mean(sales)
print(average_sales)

#4)
count = np.sum(sales > 200)
print(count)

#5)
total_expected_sales = np.sum(expected_sales)
print(total_expected_sales)

Tablet
Jun
210.83333333333334
11
5566.0
